[package]
name = "litearrow-core"
version.workspace = true
edition.workspace = true

[dependencies]
arrow-array.workspace = true
arrow-buffer.workspace = true
arrow-data.workspace = true
arrow-ipc.workspace = true
arrow-schema.workspace = true
litearrow-compression = { path = "../litearrow-compression" }
